### ISSUE TITLE
【産総研】【要対応】C/C++の警告

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/navigation#1]
- 指摘カテゴリ：C/C++の警告 
- チェッカー名：CWARN.DTOR.NONVIRT.NOTEMPTY,CWARN.DTOR.NONVIRT.DELETE
- 指摘重要度：エラー

仮想(virtual)デストラクタが定義されていないことにより、メモリリークする可能性があるため、
修正する。

**Comment by r-kurose** [comment]
2020-01-20 レビュー記録確認完了
