### ISSUE TITLE
【産総研】【対応対象外】現実的にはNULLチェック不要な箇所への指摘(base_local_planner) 

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/navigation#10]
### 今回対象外としたKlocwork上で表示されるエラー指摘
1. /home/devel/project/ws_navigation/src/navigation/base_local_planner/src/point_grid.cpp
- 行 375 の関数 'PointCloud2ConstIterator<float>' の呼び出しによって返されるポインタ 'iter_z.data_' は、NULL の場合があり、行 380 で逆参照される場合があります。
- 行 373 の関数 'PointCloud2ConstIterator<float>' の呼び出しによって返されるポインタ 'iter_x.data_' は、NULL の場合があり、行 384 で逆参照される場合があります。
- 行 374 の関数 'PointCloud2ConstIterator<float>' の呼び出しによって返されるポインタ 'iter_y.data_' は、NULL の場合があり、行 385 で逆参照される場合があります。
- 行 502 の関数 'PointCloud2Iterator<float>' の呼び出しによって返されるポインタ 'iter_x.data_' は、NULL の場合があり、行 508 で逆参照される場合があります。
- 行 503 の関数 'PointCloud2Iterator<float>' の呼び出しによって返されるポインタ 'iter_y.data_' は、NULL の場合があり、行 509 で逆参照される場合があります。
- 行 504 の関数 'PointCloud2Iterator<float>' の呼び出しによって返されるポインタ 'iter_z.data_' は、NULL の場合があり、行 510 で逆参照される場合があります。

2. /home/devel/project/ws_navigation/src/navigation/base_local_planner/src/voxel_grid_model.cpp

- 行 197 の関数 'PointCloud2ConstIterator<float>' の呼び出しによって返されるポインタ 'iter_z.data_' は、NULL の場合があり、行 203 で逆参照される場合があります。
- 行 195 の関数 'PointCloud2ConstIterator<float>' の呼び出しによって返されるポインタ 'iter_x.data_' は、NULL の場合があり、行 207 で逆参照される場合があります。
- 行 196 の関数 'PointCloud2ConstIterator<float>' の呼び出しによって返されるポインタ 'iter_y.data_' は、NULL の場合があり、行 208 で逆参照される場合があります。
- 行 293 の関数 'PointCloud2Iterator<float>' の呼び出しによって返されるポインタ 'iter_x.data_' は、NULL の場合があり、行 303 で逆参照される場合があります。
- 行 294 の関数 'PointCloud2Iterator<float>' の呼び出しによって返されるポインタ 'iter_y.data_' は、NULL の場合があり、行 304 で逆参照される場合があります。
- 行 295 の関数 'PointCloud2Iterator<float>' の呼び出しによって返されるポインタ 'iter_z.data_' は、NULL の場合があり、行 305 で逆参照される場合があります。

#8 と同様の指摘。

**Comment by sec-matsunaga** [comment]
```
  sensor_msgs::PointCloud2 cloud;
  sensor_msgs::PointCloud2Modifier modifier(cloud);
  modifier.setPointCloud2FieldsByString(1, "xyz");
  Observation ob1(cloud, 1.0);
  obs.push_back(ob1);
```
のような設定をすることで、本指摘の箇所で、PointCloudの値を設定せずに指摘箇所の関数の呼び出しが可能であった。

ただし、#8 でコメントいただいたように、 if(iter_z != iter_z.end())を実施することで、
該当データが存在しないことのチェックが可能なため、*iter_zによるセグメンテーションフォルト
を回避することが出来る。（該当箇所は、
 for(; iter_x != iter_x.end(); ++iter_x, ++iter_y, ++iter_z){
によるループであり、上記の入力であれば、
「iter_x != iter_x.end();」の終了条件で回避できているので修正を入れるべきなのかは微妙である。

ただし、 上記対処を入れても静的解析の指摘は取り除かれない。(*iter_zがNULLであることと
iter_zの値が存在していないことが等価ではないと判断されていると思われる。）

修正自体としては、
```
const sensor_msgs::PointCloud2& cloud = *(obs.cloud_);
if( cloud.data.size() == 0 ){
```
のようにデータの数がゼロであることを明にチェックする方が可読性の点で
良い可能性もある。

**Comment by r-kurose** [comment]
これは上記コメントにより、動作上は回避できている問題になっている。
発生原因は今回の修正対象の外であるため、修正しない。
