### ISSUE TITLE
【産総研】【要対応】デストラクタが仮想化されていないことによるメモリリーク(global_planner)

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/navigation#13]
- 指摘カテゴリ：メモリリーク 
- チェッカー名：CL.MLK.VIRTUAL
- 指摘重要度：エラー

 #1  の指摘と同根。デストラクタが仮想化されていないため、メモリリークする可能性がある。

**Comment by r-kurose** [comment]
@sec-matsunaga 
本件はどの PR とも紐付いていません。確認ください。

**Comment by sec-matsunaga** [comment]
#1 で対応したPRが本件の対応にもなっております。
#1 と合わせてクローズしていただけると助かります。（#1 のPRのコミットログに#13も含めるべきだったかもしれません。）

**Comment by r-kurose** [comment]
#52 で完了
