### ISSUE TITLE
【産総研】【要対応】メモリ解放漏れ(navfn)

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/navigation#14]
- 指摘カテゴリ：メモリリーク 
- チェッカー名：MLK.MUST
- 指摘重要度：エラー

mallocで確保したメモリの解放が行われていない。（ただし、本メモリを開放するタイミングは、main処理終了時点なので、解放漏れによる実際の動作上の影響はない。）
mallocで確保したメモリはソース中で解放する処理を入れておくべきではあるので、修正する。

**Comment by r-kurose** [comment]
2020-01-20 レビュー記録確認完了
