### ISSUE TITLE
【産総研】【対応対象外】リソース解放漏れの指摘

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/navigation#15]
### 今回対象外としたKlocwork上で表示されるエラー指摘
1. /home/devel/project/ws_navigation/src/navigation/amcl/src/amcl_node.cpp
- 行 315 で   'new(sizeof(AmclNode))->laser_scan_filter_->target_frames_mutex_.m'   に割り当てられたリソースが失われる可能性があります。
- 行 315 で   'new(sizeof(AmclNode))->laser_scan_filter_->failure_signal_mutex_.m'   に割り当てられたリソースが失われる可能性があります。

### 以下、詳細

対象のソースコード：amcl/src/amcl_node.cpp
```
    305 int
    306 main(int argc, char** argv)
    307 {
    308   ros::init(argc, argv, "amcl");
    309   ros::NodeHandle nh;
    310
    311   // Override default sigint handler
    312   signal(SIGINT, sigintHandler);
    313
    314   // Make our node available to sigintHandler
    315   amcl_node_ptr.reset(new AmclNode());
    316
    317   if (argc == 1)
    318   {
    319     // run using ROS input
    320     ros::spin();
    321   }
    322   else if ((argc == 3) && (std::string(argv[1]) == "--run-from-bag"))
    323   {
    324     amcl_node_ptr->runFromBag(argv[2]);
    325   }
    326
    327   // Without this, our boost locks are not shut down nicely
    328   amcl_node_ptr.reset();
    329
    330   // To quote Morgan, Hooray!
    331   return(0);
    332 }
```
315行目で設定したAmclNodeのメンバ変数である「laser_scan_filter_」と「laser_scan_sub_」の
中のメンバ変数「boost::mutex target_frames_mutex_; 」の解放漏れを指摘している。
実際には、
```
    981 AmclNode::~AmclNode()
    982 {
    983   delete dsrv_;
    984   freeMapDependentMemory();
    985   delete laser_scan_filter_;
    986   delete laser_scan_sub_;
    987   // TODO: delete everything allocated in constructor
    988 }
```
のデストラクタの中で、「laser_scan_filter_」と「laser_scan_sub_」のデリート処理が実施されている。
```
00663   tf2::BufferCore& bc_; 
00664   V_string target_frames_; 
00665   std::string target_frames_string_;
00666   boost::mutex target_frames_mutex_; 
00667   uint32_t queue_size_; 
```
「target_frames_mutex_」は、ポインタ等で動的に生成されているわけではないので、
「laser_scan_filter_」と「laser_scan_sub_」を削除すれば削除されるはずである。
よってこれは誤指摘であると判断した。

**Comment by r-kurose** [comment]
Klocwork が問題であったかの確認は取れていない。
確認するべきだが、分析上では問題無いということで終了する。
