### ISSUE TITLE
【産総研】【要対応】メンバ変数の初期化漏れ（amcl）

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/navigation#23]
- 指摘カテゴリ：未初期化のデータの使用 
- チェッカー名：UNINIT.HEAP.MIGHT,UNINIT.CTOR.MUST
- 指摘重要度：重大,エラー

メンバ変数の未初期化（UNINIT.CTOR.MUST）及び
配列の未初期化と配列の要素を指定するインデックスの範囲チェック不足（UNINIT.HEAP.MIGHT)
が指摘されている。なおインデックスの範囲チェック不足については、実際には配列の範囲外
（未初期化部分）へのアクセスの可能性を指摘されている。未初期化としてまとめられているのはそのためである。

**Comment by r-kurose** [comment]
2020-01-20 レビュー記録確認完了
