### ISSUE TITLE
【産総研】【要対応】メンバ変数の初期化漏れ（carrot_planner）

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/navigation#25]
- 指摘カテゴリ：未初期化のデータの使用 
- チェッカー名：UNINIT.CTOR.MUST
- 指摘重要度：エラー

メンバ変数のコンストラクタでの未初期化のみ。

**Comment by r-kurose** [comment]
2020-01-20 レビュー記録確認完了
