### ISSUE TITLE
【産総研】【要対応】メンバ変数の初期化漏れ（base_local_planner)

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/navigation#29]
- 指摘カテゴリ：未初期化のデータの使用 
- チェッカー名：UNINIT.CTOR.MIGHT,UNINIT.CTOR.MUST
- 指摘重要度：重大,エラー

メンバ変数のコンストラクタでの未初期化
及び、メンバ変数がコンストラクタで未初期化になるパスが存在する
の二つが指摘されている（後者は通常は初期化されるが、あるケースで初期化されないという意味）

**Comment by r-kurose** [comment]
レビュー結果の確認完了
