### ISSUE TITLE
 【産総研】【要対応】NULLチェック漏れの指摘

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/navigation#3]
### 本Issueで指摘されているKlocwork上の指摘
1. /home/devel/project/ws_navigation/src/navigation/costmap_2d/plugins/inflation_layer.cpp
- 行 357 の NULL チェック前のポインタ 'this->cached_distances_' の逆参照は問題となる可能性があります

### 以下、詳細
- 指摘カテゴリ：NULL ポインタの逆参照 
- チェッカー名：RNPD.DEREF
- 指摘重要度：重大
-  対象ソース：navigation/costmap_2d/plugins/inflation_layer.cpp

```
    343   if (cached_distances_ != NULL)
    344   {
    345     for (unsigned int i = 0; i <= cached_cell_inflation_radius_ + 1; ++i)
    346     {
    347       if (cached_distances_[i])
    348         delete[] cached_distances_[i];
    349     }
    350     if (cached_distances_)
    351       delete[] cached_distances_;
    352     cached_distances_ = NULL;
    353   }
```
350行目でのNULLチェックをする前に347行でアクセスしているという指摘だが、
実際には、343行目でcached_distances_自体へのNULLチェックは実施済みのため、
再度NULLチェックを入れる必要はない。よって対象外とする。

**Comment by r-kurose** [comment]
@sec-matsunaga 
本件には何の PR も紐付けられていません。確認願います。

**Comment by sec-matsunaga** [comment]
【KW:7711】NULL参照の指摘について
にて、KlocWorkに問い合わせ中。

【回答】
本指摘に関しまして、Klocworkはスレッド間のタイミングに関しては考慮していません。
そのため、mutex lockなどで共有資源に関するアクセスの排他制御の無い状況で、グローバル
変数による共有領域へのアクセスを行う処理に対してNULL参照の危険性を指摘します。

**Comment by sec-matsunaga** [comment]
Klocworkの指摘にあるように、確かに排他制御をしていないので、スレッドセーフではない。
本処理がマルチスレッドで使われるものなのかチェックする必要がある。

この処理の呼び出しもとはコールバック関数
```
     88     dynamic_reconfigure::Server<costmap_2d::InflationPluginConfig>::CallbackType cb = boost::bind(
     89         &InflationLayer::reconfigureCB, this, _1, _2);
```
としても利用されており、マルチスレッド的な使われ方をする可能性がありうる。
よってmutexによる排他を実施すべきと考えられる。

**Comment by r-kurose** [comment]
設計として受け入れられるかはさておき、シーケンス上 mutex なしに cached_distances_ にアクセスして良いかどうかの判断は使用箇所が多すぎて難しい。そのため、安全側に倒して、変数アクセス箇所をすべて mutex でカバーすることとする。

**Comment by sec-matsunaga** [comment]
chached_distances_へのアクセスする箇所について再確認したところ、
boost::unique_lock < boost::recursive_mutex > lock(*inflation_access_);
を使って、1か所を除いてロック処理が行われていた。
その1か所は、onFootprintChangedであり、上記ロックを行わずに、
chached_distances_へアクセスするメソッドを使用している。
ここに上記のlockを設定することで問題が回避できると考えられる。
~~（Klocworkの指摘上も指摘は消える。)~~
実際に消えているように見えたのは、

```
    350     if (cached_distances_)
    351       delete[] cached_distances_;
    352     cached_distances_ = NULL;
```
mutexをかけることによって、
```
    351     delete[] cached_distances_;
    352     cached_distances_ = NULL;
```
の350行目のif文が不要になると考え（実際には、mutexの有無にかかわらず350行目の意味はあまりないと思うが）、NULLチェックを外したことによって、指摘が消えていた模様。
試しに、350行目だけ復活させたところ指摘が再現したため。

**Comment by r-kurose** [comment]
レビュー結果の確認完了

**Comment by sec-matsunaga** [comment]
結局のところ、Klocworkとしては、下記の内容でチェックしていたとの回答あり。

【Klocworkからの最終回答】
このチェッカーは、逆参照されている変数のNULLチェックの有無を確認しています。
350行目での"cached_distances_"のNULLチェックは、常に"true"となるためにチェック
は不要であるとの指摘です。
