### ISSUE TITLE
【産総研】【要対応】外部からの入力値を検証なしで使用している（amcl) 

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/navigation#43]
- 指摘カテゴリ：未検証のユーザー入力 
- チェッカー名：SV.TAINTED.ALLOC_SIZE、SV.TAINTED.LOOP_BOUND、SV.TAINTED.INDEX_ACCESS
- 指摘重要度：重大、エラー

```
fscanf(file, " %d %d \n %d \n", &width, &height, &depth)
```

によって、設定されるwidthやheightの値をノーチェックで利用していることを問題としている。
（width×heightをメモリの確保などに利用するため）

**Comment by r-kurose** [comment]
レビュー結果の確認完了
