### ISSUE TITLE
【産総研】【要対応】外部からの入力値を検証なしで使用している（navfn) 

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/navigation#44]
- 指摘カテゴリ：未検証のユーザー入力 
- チェッカー名：SV.TAINTED.ALLOC_SIZE、SV.TAINTED.LOOP_BOUND、SV.TAINTED.INDEX_ACCESS
- 指摘重要度：重大、エラー

外部からの引数で設定される値を未検証のまま利用しているため、メモリの確保などで問題が発生する可能性を指摘している。

**Comment by r-kurose** [comment]
レビュー結果の確認完了

**Comment by sec-matsunaga** [comment]
1点修正を加えさせてください。
std::numeric_limits
を利用するためのヘッダとしては、「#include <limits>」とすべきでした。（拡張子除く）
上記修正を実施したプルリクを送ります。

limits.hとして手元のUbuntu環境ではビルドが通ったので見過ごしてしまいました。
申し訳ありません。

上記対応に伴い、本Issueを一旦再オープンいたします。
#90 が対応するプルリクになります。

**Comment by r-kurose** [comment]
マージ完了です。
