### ISSUE TITLE
 【産総研】【要対応】ゼロ除算が発生する可能性があるコード（amcl) 

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/navigation#45]
1.  /home/devel/project/ws_navigation/src/navigation/amcl/src/amcl/pf/pf.c
・ 'weight' がゼロ除算で使用されている可能性があります
・ 'mn' がゼロ除算で使用されている可能性があります

### 以下、詳細

- 指摘カテゴリ：無効な算術演算です
- チェッカー名：DBZ.GENERAL
- 指摘重要度：重大

double型の変数に0.0を設定した状態で、除算を実施する可能性があるコードである。

**Comment by r-kurose** [comment]
2020-01-20 レビュー記録確認完了

**Comment by sec-matsunaga** [comment]
★今回修正済だが、Klocworkの誤指摘により、以下の指摘は解除されない。
のコメント追加により、再確認を実施していただくため、再オープンする。

なお、「 'mn' がゼロ除算で使用されている可能性があります」の対応がマージ漏れしていたため、
別のプルリクエストで再度追加する。

**Comment by sec-matsunaga** [comment]
修正後も指摘が残る件は、 #88 に引き継ぐ。

**Comment by r-kurose** [comment]
レビュー結果の確認完了。
