### ISSUE TITLE
【産総研】【要対応】未初期化データ利用の指摘（global_planner）

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/navigation#47]
- 指摘カテゴリ：未初期化のデータの使用 
- チェッカー名：UNINIT.CTOR.MUST
- 指摘重要度：エラー

コード中で該当する変数の利用時に必ず初期化され、それ以外では利用されていない変数であったので、対象外としていたが、原則修正するという方針にあわせて、修正を実施した。

**Comment by r-kurose** [comment]
2020-01-20 レビュー記録確認完了
