### ISSUE TITLE
【産総研】【対応対象外】未初期化データ利用の指摘（global_planner）

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/navigation#48]
対象コード：global_planner/include/global_planner/planner_core.h
```
    171         costmap_2d::Costmap2D* costmap_;
    172         std::string frame_id_;
    173         ros::Publisher plan_pub_;
    174         bool initialized_, allow_unknown_, visualize_potential_;
```
のvisualize_potential_が未初期化という指摘だが、

```
    171         costmap_2d::Costmap2D* costmap_;
    172         std::string frame_id_;
    173         ros::Publisher plan_pub_;
    174         bool initialized_, allow_unknown_;
```
melodic-develの最新版（commit ded1abcb37815e8eb4ea2b733e1c3ec02b25e7ad）では、
上記のように変数自体が削除されているので、
対応しない（melodic-develの最新版では対処済み）。

**Comment by r-kurose** [comment]
@sec-matsunaga 
記載されているコミット番号が間違っているのか、該当の部分が見つかりません。

**Comment by sec-matsunaga** [comment]
【対応対象外】の項目ですので、PRは出しておりません。
上記コメントしている通り、最新版では既に該当の未初期化変数が削除されているため、未対応になります。（最新版では既存のコードがKlocworkの指摘に対応している形になります。）

**Comment by r-kurose** [comment]
ded1abc が「該当変数の削除」コミットへのリンクを張り間違えたのだと勘違いしていました。
該当コミットは、 3dcd73a0479adc6883229526e9810133223d67f0 のようですね。
静的解析対応済みブランチとしたいので、このコミットを git cherry-pick で拾って、静的解析ブランチに取り込んでもらえないでしょうか。

**Comment by sec-matsunaga** [comment]
黒瀬様の指摘を勘違いしておりました。おっしゃる通り「 ded1abc 」はmasterの最新を示しているだけで、実際に取り込まれたコミットは、「 3dcd73a 」になります。「 3dcd73a 」自体は、既に静的解析ブランチに取り込み済み（昨年度の解析時はまだ未対応でしたが、今回「静的解析ブランチ」を作成したのは、最新のmelodic-develから分岐しているので）です。

**Comment by r-kurose** [comment]
静的解析対応を開始時点で取り込み済と理解しました。
