### ISSUE TITLE
【産総研】【要対応】未初期化データ利用の指摘（global_planner）(利用時に必ず初期化されるケース)

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/navigation#49]
#24 の中で対処済み。（利用時に必ず初期化される変数(potential_arraay_)だったため、対象外としていたが、極力直す方針にあわせて、初期化を実施した。）

**Comment by r-kurose** [comment]
@sec-matsunaga 
#48 とタイトルが同じです。確認ください。

**Comment by sec-matsunaga** [comment]
タイトルを修正しました。
