### ISSUE TITLE
 【産総研】【要対応】Nullを返却する関数の戻り値に対してのNullチェック(map_server)

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/navigation#5]
- 指摘カテゴリ：NULL ポインタの逆参照  
- チェッカー名：NPD.FUNC.MUST
- 指摘重要度：重大

fopen失敗時にNULLが返却されるため、NULLチェックを追加する。

**Comment by r-kurose** [comment]
2020-01-20 レビュー記録確認完了
