### ISSUE TITLE
【産総研】【対応対象外】未初期化データ利用の指摘（amcl）

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/navigation#50]
### 今回対象外としたKlocwork上で表示されるエラー指摘
1. /home/devel/project/ws_navigation/src/navigation/amcl/src/amcl/sensors/amcl_laser.cpp
- '*obs_count' では、初期化されていないヒープメモリ領域から値を取得している可能性があります。

### 以下、詳細

対象のコード：amcl/src/amcl/sensors/amcl_laser.cpp

```
    346   //we need a count the no of particles for which the beam agreed with the map
    347   int *obs_count = new int[self->max_beams]();
    348
    349   //we also need a mask of which observations to integrate (to decide which beams to integrate to all particles)
    350   bool *obs_mask = new bool[self->max_beams]();
    351
```
上記のコードで定義している「obs_count」および「obs_mask」をKlocworkでは未初期化と判断している。実際には、「new int\[N\]()」と定義した場合は、配列はゼロで初期化される。
メーカに確認したところ、誤指摘との回答があったため、本件は修正対象外とする。

**Comment by r-kurose** [comment]
Klocwork の問題だったので、対応不要で終了します。

**Comment by sec-matsunaga** [comment]
★今回対象外としたKlocwork上で表示されるエラー指摘
を追記に伴い、追記の確認を実施していただくため再オープン。

**Comment by sec-matsunaga** [comment]
【KW:7657】配列の初期化指摘について
【連絡】
本件は、ローグウェーブ社のサポートサイトで、最新の環境（2019.3）で再現する
事を確認しました。
本件は、誤検知として開発の案件に登録して対応いたします。
リリース時期等に関しては未定です。

## 再現確認用のサンプル

エラー再現用のサンプルコード
```
int main(int argc, char* argv[]){
  int N = argc;
  int *array;
  array = new int[N];

  int *array2;
  array2 = new int[N]();
  printf("%p,%p\n", array, array2);
  for(int i = 0; i < N; i++ ){
    printf("%d,%d\n",array[i], array2[i]);
  }
  delete[] array;
  delete[] array2;
```
サンプルの11行目（array = new int[N];)は確かに未初期化なので
指摘がでるのはOK（正常）なのですが、

サンプルの14行目で（array2 = new int [N] ();)でゼロ初期化した
場合でも、同じようにarray2は未初期化ですと
指摘されてしまいます。

**Comment by r-kurose** [comment]
ツールの問題であることが確認されたので閉じます。
