### ISSUE TITLE
【産総研】【要対応】ポインタ変数のNullチェック(move_base) 

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/navigation#6]
- 指摘カテゴリ：NULL ポインタの逆参照  
- チェッカー名：RNPD.CALL、NPD.FUNC.MUST
- 指摘重要度：重大

ポインタのNULLチェックが不足しているため追加する。

**Comment by sec-matsunaga** [comment]
> Question:
> Is this pointer can be deleted by delete()?
> Is there the release function corresponding to acceptNewGoal()?

上記のコメントをいただいております。
acceptNewGoal()の戻り値は、boost::shared_ptrであるため、明示的なdelete処理はないと
思いますが、いかがでしょうか。

**Comment by r-kurose** [comment]
@sec-matsunaga 
私は ```acceptNewGoal()``` の型を知らないので、こうした質問になっています。
#6 の指摘を閉じたいので、その返答を #6 に記述してください。

**Comment by sec-matsunaga** [comment]
#6 に記載とのことでしたので、ここの #6 のコメント欄に記載させていただきます。一応プルリク側にも同様のコメントを残します。
acceptNewGoalの型としては、以下に示すようにboost::shared_ptrとなっております。
```
boost::shared_ptr<const move_base_msgs::MoveBaseGoal_<std::allocator<void> > > new_goalPtr = as_->acceptNewGoal();
```
この元は、
```
as_ = new MoveBaseActionServer(ros::NodeHandle(), "move_base", boost::bind(&MoveBase::executeCb, this, _1), false);

move_base/include/move_base/move_base.h:64:  typedef actionlib::SimpleActionServer<move_base_msgs::MoveBaseAction> MoveBaseActionServer;
```
であり、さらに、「actionlib::SimpleActionServer」は、
```
server/simple_action_server.h:139:  boost::shared_ptr<const Goal> acceptNewGoal();
```
という形で、「boost::shared_ptr」を返すようになっております。
よって、明示的にdeleteすることはありません。
