### ISSUE TITLE
【産総研】【対応対象外】ゼロ除算が発生する可能性があるコード（amcl) 

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/navigation#88]
1.  /home/devel/project/ws_navigation/src/navigation/amcl/src/amcl/pf/pf.c
・ 'weight' がゼロ除算で使用されている可能性があります
・ 'mn' がゼロ除算で使用されている可能性があります

本件は #45 で一度対応している。しかし、Klocworkの仕様により、指摘は消えない。
以下、Klocworkからの回答

**Comment by sec-matsunaga** [comment]
Klocworkからの回答

【内容】
本件は、誤検知となります。

調査の結果、コンパイル中にDBL_EPSILONが次の値に置き換えられているようです：
double（2.22044604925031308084726333618164062e-16L）
Klocworkチェッカーはこの値を誤って評価し、その結果をNaN(Not a Number)として比較を行い
IFステートメントをfalseとして判定し、ゼロによる除算が存在するELSEステートメントに移行する
結果となるようです

さらに、fabs（）関数を使用する場合、同様の理由で、Klocworkチェッカーはすべての比較をFalseと
評価してDBZ.GENERALが検出されていたそうです。

本件は、ローグウェーブ社の開発に報告されて、修正対象のリストに入りました。
然し、対応時期に関しては未定のため、対応された版がリリースされる際に再度連絡とさせて
いただきます。

**Comment by r-kurose** [comment]
ツールの問題であることが確認されたので閉じます。
