### ISSUE TITLE
 【産総研】【要対応】Nullを返却する関数の戻り値に対してのNullチェック(amcl/pf/)

### ISSUE THREAD

**Issue by sec-matsunaga** [robo-marc/navigation#9]
- 指摘カテゴリ：NULL ポインタの逆参照  
- チェッカー名：NPD.FUNC.MUST,NPD.FUNC.MIGHT
- 指摘重要度：重大

malloc、callocの戻り値としてNULLが返る可能性があるため、NULLチェックを追加する。

**Comment by r-kurose** [comment]
2020-01-20 レビュー記録確認完了
